### ISSUE TITLE
打开

### ISSUE THREAD

**Issue by dongyu23** [methylbenzene/DingTalkAddLikes#1]
我是小白，我只认exe，这个玩意怎么打开。。。。

**Comment by methylbenzene** [comment]
https://gh.api.99988866.xyz/https://raw.githubusercontent.com/methylbenzene/DingTalkAddLikes/main/DingTalkLikes.exe  

打开程序乱码安装字体'SourceHanSansCN-Normal'  
https://gh.api.99988866.xyz/https://raw.githubusercontent.com/RaymondClr/SourceHansTtf/master/SourceHanSansCN-Normal.ttf

**Comment by m3ma110c** [comment]
https://github.com/m3ma110c/DingTalkAddLikes/releases/download/e/DingTalkLikes.exe
