### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by yehuzhucha** [methylbenzene/DingTalkAddLikes#2]
您好，我使用的是Windows7以及最新版的钉钉。进入直播间后开启的点赞，然而并没有效果，不知道是不是因为阿里封掉了这个接口所导致的？

**Comment by Wkuny** [comment]
好像是的
现在用的这东西好像是用钉钉直播点赞的API接口"https://lv.dingtalk.com/interaction/createLike?uuid=xxxx&count=xxxx"实现的
（我不是作者我只是在猜）
现在这个API吧把参数写上去之后没有返回success了

**Comment by Brassinolide** [comment]
是的，该接口已被封禁，请使用nextgen
